#!/bin/bash
echo "Nb_threads,Measure_1,Measure_2,Measure_3,Measure_4,Measure_5" > prcon.csv

gcc -o producers_consumers prconver.c -pthread || { echo "Compilation failed!"; exit 1; }
for total_threads in 2 4 8 16 32; do
    echo -n "Threads: $total_threads"
    num_producers=$((total_threads / 2))
    num_consumers=$((total_threads / 2))
    echo -n "$total_threads," >> prcon.csv
    for _ in 1 2 3 4 5; do
        TIME=$( { time ./producers_consumers $num_producers $num_consumers > /dev/null; } 2>&1 | grep real | awk '{print $2}')
        echo -n "$TIME;" >> prcon.csv
    done
    echo "" >> prcon.csv
done

# Message de fin
echo "Mesures collectées et enregistrées dans prcon.csv"
